---
label: Project
hide_body: false
is_partial: false
fields:
- type: text
  name: layout
  label: layout
  default: default
- type: text
  name: title
  label: title
- type: text
  name: permalink
  label: permalink
  default: "/projects/template"
- type: text
  name: date
  label: date
- type: textarea
  name: description
  label: description
  default: Enter description here
pages:
- _projects/2018-08 generative_business_cards.md
- _projects/2018-10 face_instrument.md
- _projects/2017-09 interactive_comics.md
- _projects/2018-02 pattern_generator.md
- _projects/2017-05 cthulhu_tarot.md
- _projects/2016-03 perceptual_shift.md
- _projects/2017-12 embol.md
- _projects/2016-10 nymero.md
- _projects/2015-12 sprite_generator.md
